# This file created by conda-build 2.0.11+6.g43b927b
# meta.yaml template originally from:
# /home/ray/conda/anaconda/packages/pcre, last modified Mon Dec  5 23:52:35 2016
# ------------------------------------------------

package:
    name: pcre
    version: '8.39'
source:
    patches:
        - 0001-Add-a-new-option-for-controlling-static-builds-with-.patch
    sha1: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
    url: http://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz
build:
    number: '1'
    string: '1'
requirements:
    build: !!python/object:__builtin__.instancemethod {}
    run:
        - zlib 1.2.*
about:
    description: 'The PCRE library is a set of functions that implement regular expression

        pattern matching using the same syntax and semantics as Perl 5. PCRE has

        its own native API, as well as a set of wrapper functions that correspond

        to the POSIX regular expression API. The PCRE library is free, even for

        building proprietary software.

        '
    dev_url: http://vcs.pcre.org/pcre2/
    doc_url: http://www.pcre.org/original/doc/html/
    home: http://www.pcre.org/
    license: 3-clause BSD License
    license_family: BSD
    summary: A set of functions that implement regular expression pattern matching
