package:
  name: networkx
  version: "1.11"

source:
  fn: networkx-1.11.tar.gz
  url: https://pypi.python.org/packages/source/n/networkx/networkx-1.11.tar.gz
  md5: 6ef584a879e9163013e9a762e1cf7cd1

requirements:
  build:
    - python
    - setuptools
    - decorator
  run:
    - python
    - decorator >=3.4

about:
  home: http://networkx.lanl.gov/
  license: BSD
  license_file: LICENSE.txt
  summary: Python package for creating and manipulating graphs and networks
