# This file created by conda-build 2.0.11+6.g43b927b
# meta.yaml template originally from:
# /home/ray/conda/anaconda/packages/pixman, last modified Mon Dec  5 23:52:35 2016
# ------------------------------------------------

package:
    name: pixman
    version: 0.34.0
source:
    md5: e80ebae4da01e77f68744319f01d52a3
    patches: ''
    url: http://cairographics.org/releases/pixman-0.34.0.tar.gz
build:
    features: ''
    string: '0'
requirements:
    build: []
about:
    description: 'Pixman is a low-level software library for pixel manipulation,

        providing features such as image compositing and trapezoid

        rasterization. Important users of pixman are the cairo graphics

        library and the X server.

        '
    dev_url: https://cgit.freedesktop.org/pixman/
    home: http://www.pixman.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: A low-level software library for pixel manipulation
